services:
  database:
    container_name: editor-database
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PORT: 5430
      POSTGRES_DB: editor
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "54320:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - back
  app-back:
    container_name: editor-app-back
    restart: always
    build:
      context: ./back
      dockerfile: Dockerfile
    env_file:
      - ./back/.env
    depends_on:
      - database
    ports:
      - "3000:3000"
    networks:
      - back
  app-front:
    container_name: chat-app-front
    restart: always
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - app-back
    networks:
      - back
      - front
volumes:
  db_data:

networks:
  back:
    driver: bridge
  front:
    driver: bridge